name: pinnacle
description: Pinnacle Flutter app
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Design & UI
  google_fonts: ^6.1.0 # For the 'Inter' font
  flutter_svg: ^2.0.9 # For handling SVG icons

  # State & Routing
  flutter_riverpod: ^3.1.0
  go_router: ^17.0.1

  # Storage & Networking (Pre-adding for Phase 2)
  dio: ^5.4.0
  flutter_secure_storage: ^10.0.0
  url_launcher: ^6.2.5
  lucide_icons_flutter: ^3.1.9
  intl: ^0.20.2
  google_sign_in: ^7.2.0
  logger: ^2.6.2
  flutter_pdfview: ^1.4.4
  printing: ^5.14.2
  pdf: ^3.11.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/launcher/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.3

flutter_launcher_icons:
  android: true
  ios: true

  image_path_android: assets/launcher/launcher_icon.png
  adaptive_icon_background: '#020617'
  adaptive_icon_foreground: assets/launcher/launcher_icon.png

  image_path_ios: assets/launcher/launcher_icon.png

flutter_native_splash:
  color: '#020617'
  image: 'assets/launcher/launcher_icon.png'
  android: true
  ios: true
  web: false
